### PR TITLE
Enable CodeQL github action codeql.yml

### PR DESCRIPTION
**Pull request by zdaratom**
Enable CodeQL github action codeql.yml

### CODE REVIEW

**Comment by martin-majlis-s1** [comment]
I would say that this check should be passing before I accept it.

I have solved it in this PR - https://github.com/scalyr/dataset-addon-for-splunk/pull/41 - with ignoring all errors and crazy defaults.

**Comment by martin-majlis-s1** [comment]
It looks to me, that it's failing - https://github.com/scalyr/dataset-addon-for-splunk/security/code-scanning/tools/CodeQL/status

**Comment by zdaratom** [comment]
You were to fast, it is passing :) and 

> Once you merge this pull request, the 'Security' tab will show more code scanning analysis results

**Comment by zdaratom** [comment]
> It looks to me, that it's failing - https://github.com/scalyr/dataset-addon-for-splunk/security/code-scanning/tools/CodeQL/status

those are results from my previous attempt to set it up without explicit config file, see https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-default-setup-for-code-scanning#configuring-default-setup-for-a-repository

**Review by martin-majlis-s1 — APPROVED** [review]
Can you somehow check, that it's really scanning the code?

I can imagine that if there is incorrect configuration - it's checking incorrect folder - it will pass, although the code is not safe.

**Pull request merged**
