### PR TITLE
refactor and improve tests

### PR DESCRIPTION
**Pull request by zdaratom**
- speedup tests, remove redundant steps and unused code
- improve readability
- rename methods 
- improve logging
- improve asserts (verify splunk alert results in DataSet)

### CODE REVIEW

**Review by martin-majlis-s1 — COMMENTED** [review]
The original idea was to make sure that interaction with the application works. So it's "go to HP => click on menu item =>  check that we are on the correct page => perform some action there".

You change is - "go to the URL => perform some action there". 

I can see that going through those pages every time is slow and could be replaces by going directly to the URL, but there still should be at least one test, that verifies that menu items are there and they lead to expected pages.

I do not have strong preference, whether it's better to have in the `inputs.spec.ts`, `examples.spec.ts`, and `search.spec.ts` a test that verifies the "click on the menu path" or whether there will be some `menu.spec.ts`

I was also trying to have the "movement" and "action" as separate functions - so it was "goToX", "performY", "performZ". Function `searchDataSet` is combining "goToX" and "performY".

**Comment by zdaratom** [comment]
Note that if the application fails to deploy test will fail no matter if you go via url or clicking through menu. Clicking through menu is imho just slower.

I understand that actions approach, on the other hand such a steps are bit more complicated to use since you need to keep context in test. I have found idempotent steps be more convinient.

**Comment by martin-majlis-s1** [comment]
When I check the current run: https://github.com/scalyr/dataset-addon-for-splunk/actions/runs/5975394444/job/16211261116?pr=74

```
  Slow test file: [chromium] › alert_action.spec.ts (3.0m)
  Slow test file: [chromium] › inputs.spec.ts (43.1s)
  Slow test file: [chromium] › examples.spec.ts (27.0s)
  Slow test file: [chromium] › search.spec.ts (20.6s)
```

With some previous run: https://github.com/scalyr/dataset-addon-for-splunk/actions/runs/5964013188/job/16178341279

```
  Slow test file: [chromium] › inputs.spec.ts (1.1m)
  Slow test file: [chromium] › search.spec.ts (42.1s)
  Slow test file: [chromium] › alert_action.spec.ts (31.3s)
  Slow test file: [chromium] › examples.spec.ts (23.6s)
  Slow test file: [setup] › global.setup.ts (15.4s)
```

The only speed up is as expected on the inputs/search since there are multiple tests. I agree, that it's fine to use url to get somewhere, but there should be at least one test for the navigation, to make sure, that it works.

**Comment by zdaratom** [comment]
I have added new test verifying that add on is deployed properly (asserting link and menu items)

**Review by martin-majlis-s1 — APPROVED** [review]
Great! Thanks :)

**Pull request merged**
