### PR TITLE
DPDV-4287: Pass the proxy settings

### PR DESCRIPTION
**Pull request by martin-majlis-s1**
Jira Link: <https://sentinelone.atlassian.net/browse/DPDV-4287>

# 🥅 Goal

Pass the proxy configuration to the library responsible for API calls.

# 🛠️ Solution

Pass the proxy configuration to the client, so that it be used for API calls.

This PR is also changing the logging of the single API call, so that the logs are available. When `logging` was used, they were not visible in logs.

# 🏫 Testing

* Use local proxy: 
  * Run proxy as docker - https://github.com/abhinavsingh/proxy.py - `docker run -it -p 8899:8899 --rm abhinavsingh/proxy.py:latest --log-level d --hostname 0.0.0.0`
* Proxy with basic auth - `docker run -it -p 8899:8899 --rm abhinavsingh/proxy.py:latest --log-level d --hostname 0.0.0.0 --basic-auth "foo:bar"`
* 
Screenshot 2023-10-30 at 10 13 11

* First 3 examples are using - `httpx` - and this is the fix, the 4th example is still using `requests` - everything is working.

* I have used search to check that all places are replaces - Screenshot 2023-10-26 at 17 03 17

# ❓ Question

It looks that we are always using http proxy even when maybe https should be used?

### CODE REVIEW

**Comment by mike-mcgrail** [comment]
LGTM

**Review by tomaz-s1 — APPROVED** [review]
Some (unit tests) would be nice, but besides that, LGTM.

**Comment by tomaz-s1** [comment]
Just to confirm, we also support proxies which requires authentication (aka specifying username and password)?

If so, how does that work in the code? I didn't see us constructing url in `protocol://<username>:<password>@<proxy address>` manner anywhere.

**Comment by tomaz-s1** [comment]
Another thing - the  admin UI shows `Host` but what you actually put there is a URI / URL and not just host.

If it expects URL (hostname with scheme), we should rename UI option name to `URL`, otherwise we should make it explicit that it expects a hostname and not a URL.

**Comment by martin-majlis-s1** [comment]
> Another thing - the admin UI shows `Host` but what you actually put there is a URI / URL and not just host.
> 
> If it expects URL (hostname with scheme), we should rename UI option name to `URL`, otherwise we should make it explicit that it expects a hostname and not a URL.

* It's not in the `TA_dataset` folder, where I was searching for it! It's in the root folder - https://github.com/scalyr/dataset-addon-for-splunk/blob/78219a26c2bb0d809c638408c11a456f34d79da0/globalConfig.json#L153 🤦 
  * https://github.com/scalyr/dataset-addon-for-splunk/blob/b206d236390c1c13e7b9e2f01f9ca8c4ee6d66b2/TA_dataset/README/ta_dataset_settings.conf.spec - is definitely not used (and it's in README folder)
  * those fields are indeed proxy_url and similar - https://github.com/scalyr/dataset-addon-for-splunk/blob/main/TA_dataset/bin/dataset_common.py#L75 Screenshot 2023-10-30 at 8 28 57

**Comment by tomaz-s1** [comment]
@martin-majlis-s1 Do we already have any unit tests for https://github.com/scalyr/dataset-addon-for-splunk/blob/78219a26c2bb0d809c638408c11a456f34d79da0/TA_dataset/bin/dataset_common.py#L75 function? If not, it would be nice to add some :)

**Comment by tomaz-s1** [comment]
I also had a look at the global UCC example you provided and our own and it seems like upstream default UCC is to take a Host (+ proxy protocol field) and in our case we want a URL with protocol.

I wonder if it would make more sense to follow upstream example for consistency reasons. Anyway, I don't want to delay / block merging of this PR, I'm also fine with using a URL as long as the field name is URL / URI or similar to make it clear it expected a URL with protocol and not just a hostname.

**Pull request merged**
